management:
  security:
    enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
#        org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/ecolab?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: sXG>lcli*8w<
logging:
  level:
    org.hibernate.SQL: debug
